"""create cartItems table

Revision ID: 32903ea6b463
Revises: 6964e4ed2f69
Create Date: 2024-09-12 22:35:14.445734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32903ea6b463'
down_revision = '6964e4ed2f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer()),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cartId'], ['shoppingCarts.id'],),
    sa.ForeignKeyConstraint(['productId'], ['products.id'],),
    sa.PrimaryKeyConstraint('id')

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartItems')
    # ### end Alembic commands ###
