"""create productImages table

Revision ID: c7709881d983
Revises: 32903ea6b463
Create Date: 2024-09-12 22:50:02.122666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7709881d983'
down_revision = '32903ea6b463'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('productImages',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('preview', sa.Boolean(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productImages')
    # ### end Alembic commands ###
